### ISSUE TITLE
Summary: Legal Updates for New European and Canadian data laws

### ISSUE THREAD

**Issue by chrissysievers** [lonelyplanet/rizzo-next#802]
The following changes need to happen to the following portions of the site, and **must be live before 12/18** to meet the new European and Canadian data laws:

**Updates Live:**
- [x] LP Kids footer https://github.com/lonelyplanet/wp-kids/issues/71 (Nick)
- [x] rizzo footer in all legacy apps https://github.com/lonelyplanet/rizzo/issues/1650 (Mateusz)
- [x] Newsletter sign up page https://github.com/lonelyplanet/gonzo/issues/349 (Mateusz)
- [x] LP Kids newsletter sign up page  https://github.com/lonelyplanet/wp-kids/issues/72 (Nick)
- [x] Travel News Daily sign up page https://github.com/lonelyplanet/wp-travelnews-frontend/issues/440 (Nick)
- [x] Contact us page https://github.com/lonelyplanet/microsites/issues/141 (Mateusz)
- [x] LP.com footer https://github.com/lonelyplanet/rizzo-next/issues/801 (Nick)
- [x] Homepage sign up box https://github.com/lonelyplanet/copilot/issues/425 (Nick)
- [x] Explore Every Day https://github.com/lonelyplanet/copilot/issues/474 (Tom)

**Comment by nickfranciosi** [comment]
fyi on the updated copy with footer form. It will look like this 👇 

![image](https://user-images.githubusercontent.com/4378776/33576257-d17718b4-d904-11e7-80c9-73368619b571.png)

![image](https://user-images.githubusercontent.com/4378776/33576287-da9caa76-d904-11e7-8577-4c305ec2673e.png)


I am assuming this is not ok and we will either have to get shorter copy or completely redesign how these components look. 
cc @chrissysievers @bpotterbaum

**Comment by nickfranciosi** [comment]
@chrissysievers also wanted to check that it is a legal request to remove the checkbox opt-in. Thanks

**Comment by nickfranciosi** [comment]
on homepage with new text 
![image](https://user-images.githubusercontent.com/4378776/33612230-8f603022-d996-11e7-8744-8d4bd53697df.png)

@chrissysievers

**Comment by andycarmstrong** [comment]
@chrissysievers @nickfranciosi On it!

**Comment by nickfranciosi** [comment]
@andycarmstrong just to clairfy the main issue is going to be on the footer on LP Kids footer lonelyplanet/wp-kids#71 and LP.com footer #801

it would be awesome if the same solution could be used for both, but also know that the kids site does not use backpack

Thanks!

**Comment by nickfranciosi** [comment]
@chrissysievers If i recall correctly the explore everyday page that @thomasthesecond has a newsletter form signup. Will that follow the same updates that are happening on the homepage?

**Comment by chrissysievers** [comment]
Correct @nickfranciosi but EED is being powered through copilot, like the homepage. Are the components shared? Good call!

cc: @thomasthesecond

**Comment by nickfranciosi** [comment]
@chrissysievers looking at the code - since the form is pretty different they do not utilize the same component, but we probably should think through a way to share this logic between forms. 

If we can just confirm that the EED form needs the same updates (same legal text, checkbox removed) I can take it from there. 

Thanks

**Comment by thomasthesecond** [comment]
The form component for Explore Every Day is here

https://github.com/lonelyplanet/copilot/blob/develop/app/assets/templates/exploreEveryDay/components/form/index.jsx

So we will need to update it also.

I agree the form can be shared somehow, at the very least in a shared folder within Copilot; I imagine it'll be used again in the future.

**Comment by chrissysievers** [comment]
I can create an issue for that @thomasthesecond. Thanks for the heads up @nickfranciosi !

**Comment by thomasthesecond** [comment]
Thanks @chrissysievers @nickfranciosi

**Comment by chrissysievers** [comment]
QA'd all issues linked here and all are correct and live. Closing this out.
